
[project]
name = "minunigram"
version = "0.1.0"
description = "Minunigram project"
readme = "README.md"
authors = [
    { name = "Sander Land" },
]
requires-python = ">=3.10"
dependencies = [
    "datasets>=2.15.0",
    "regex>=2024.11.6",
    "scipy>=1.15.3",
    "tqdm>=4.67.1",
]

[project.optional-dependencies]
dev = [
    "pytest>=7.0.0",
    "pytest-cov>=4.0.0",
]

[tool.pytest.ini_options]
testpaths = ["tests"]

[tool.ruff]
line-length = 120
target-version = "py311"
select = ["E", "F", "B", "I", "W"]

[tool.ruff.format]
quote-style = "double"
indent-style = "space"
line-ending = "auto"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
